#ifndef _LINUX_WRAPFS_NEW_IOCTL_H
#define _LINUX_WRAPFS_NEW_IOCTL_H

/*
 * DEFINITIONS FOR USER AND KERNEL CODE:
 */
#define	WRAPFS_IOCTL_SET_KEY	_IOW('x', 11, char*)
#define	WRAPFS_CRYPTO_KEY_LEN	32

#endif /* _LINUX_WRAPFS_NEW_IOCTL_H */


